version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
  
  backend:
    build: ./backend
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    env_file: .env
    ports:
      - ${WEB_PORT}:8080
    volumes:
      - ./frontend:/app